### ISSUE TITLE
15~16주차

### ISSUE THREAD

**Issue by jeontigger** [AssortRockStudy/DirectX2D#7]
# 15~16주차 Recap

## 디바이스란?
1. 디바이스
2. 컨텍스트
3. 스왑체인
## 정점이란?

# 그래픽스 파이프라인에 전체적인 공부는 알아서 목요일까지 해오기로
- 여기 적기 x

**Comment by superozing** [comment]
## 정적 라이브러리와 동적 라이브러리

정적 라이브러리: lib

동적 라이브러리: lib와 dll로 나뉨

정적 라이브러리는 암시적 링킹만 가능…?

동적 라이브러리는 정적 라이브러리와 다르게 링크를 런타임 중에 끊을 수 있음

정적 라이브러리는 lib가 .exe에 포함되어서 실행되지만

동적 라이브러리는 lib가 .exe에 포함되어 실행되기는 하지만 

lib가 들고 있는 정보가 dll과의 링크를 위한 정보이기 때문에 런타임 시 연결됨

dll은 실행 파일과 같은 곳에 두는 경우가 많음.

라이브러리로 만들면

이진 파일로 저장되어서 남들에게 코드를 보여주지 않을 수 있고

동적의 경우에 런타임 중에 링크를 끊었다 연결했다 할 수 있음.

전처리기로 암시적 링크를 걸면 동적이라고 해도 프로그램 시작 시 연결되고 프로그램 끝날 경우 링크기 끊어지기 때문에 정적과 거의 같은 동작을 함

## 디바이스란?

1. 디바이스
    
    GPU 메모리에 객체 생성과 관리 관련
    
2. 컨텍스트
    
    GPU 렌더링 관련
    
3. 스왑체인
    
    GPU의 버퍼에 그려진 그림을 메인 윈도우에 그리기.

## 정점이란?

좌표? 꼭짓점? 에 여러 정보 추가 한 것

정점을 이어서 그래픽스 파이프라인을 통해 도형을 그릴 수 있어요.

인덱스 버퍼를 사용해서 정점 개수를 줄여서 메모리를 적게 사용할 수 있다.

**Comment by zkzkzkzkzkzz** [comment]
정적 라이브러리와 동적 라이브러리
----------------
정적 라이브러리는 .lib의 확장자를 가지며 라이브러리 코드가 exe 파일 내에 저장되기 때문에,
별도의 추가 작업없이 라이브러리 함수들을 사용할 수 있다.
반면 동적 라이브러리는 .dll의 확장자를 가지며 동적 링킹에서 필요한 내용의 주소를 가지고 있다가
런타임 시 해당 주소로 가서 필요한 내용을 가져오는 방식의 라이브러리이다.

디바이스
-------------
1. 디바이스는 그래픽 장치로 실제 그래픽 리소스를 처리하고 렌더링 작업을 수행하는 주체이다
2. 컨텍스트는 디바이스에 대한 명령을 수행하고 상태를 유지하는 데 사용되는 객체이다
3. 스왑체인은 버퍼 두 개를 번갈아가며 보여주면서 화면에 출력되는 이미지가 부드럽게 전환되도록 하기위해 사용된다

정점
-------
그래픽 공간에서의 꼭짓점.
정점은 자신의 위치를 나타내는 좌표뿐만 아니라 색상, UV 등 다양한 정보를 담을 수 있는 구조체이다

**Comment by jwkim395** [comment]
## 정적 라이브러리와 동적 라이브러리
정적 라이브러리는 빌드 과정중 생성된 오브젝트 파일을 하나로 묶어서 lib를 생성하여 사용자에게 배포하는 것을 말한다.
여러 프로그램에서 같은 라이브러리를 쓸 경우 exe에 붙여지는 형식이기 때문에 메모리 사용이 늘어날 수 있다.
동적 라이브러리는 dll과 lib가 제공되는데, lib를 가상함수처럼 dll의 위치를 저장하여 사용하고 싶을 때 dll 파일로 접근해서 사용할 수 있게 한다.

## 디바이스란?
1. 디바이스
그래픽 장치(윈도우)

2. 컨텍스트
윈도우에 그릴 것을 저장하는 구조체(윈도우의 정보)

3. 스왑체인
더블 버퍼링 구조로 버퍼 두개를 번갈아가며 그리고, 전환시켜서 자연스럽게 보이도록 한다.

## 정점이란?
단순 물리 좌표 뿐만이 아닌 색상 등 여러 데이터를 저장하는 객체

**Comment by oljindudol** [comment]
# 15~16주차 Recap

## 디바이스란?
- 하드웨어 정보 객체
- 그래픽카드의 메모리관리와 객체생성을 인터페이스를 통해 명령한다.
- D3D11CreateDevice함수 호출을 통해 생성할 수 있다.

## 컨텍스트란?
- 랜더링용 객체
- D3D11CreateDevice함수 호출을 통해 생성할 수 있다.
- 랜더용 버퍼를 세팅하는 함수를 호출할 수 있다.
- 쉐이더를 세팅 할 수 있다.
- draw함수를 통해 랜더타겟뷰에 버텍스를 랜더할 수 있다.

## 스왑체인이란?
### 스왑체인이 무엇인가?
- api의 더블버퍼링 같은존재
- 컨텍스트로 랜더타겟뷰에 랜더를 하다가 m_SwapChain->Present함수를 쓰면 메인화면으로 옮겨주는듯?

### 어떻게 만드는가?
- DXGI_SWAP_CHAIN_DESC 구조체를 채운다
- Device객체의 CreateSwapCahin를 정의후 호출

### 추가사항
#### 랜더타겟용 버퍼(메모리 블록)
- 스왑체인을 만들면 같이생성
- 스왑체인이 관리
- gpu메모리 사용

## 정점이란?
- 화면에 그리려는 랜더의 대상, api에서 썻던 점(좌표)의 확장
- 구조체를 확장함을 통해 좌표이외의 색상정보,UV좌표계(에셋 상대좌표계)등을 멤버로 갖고있다.
- 쉐이더를 통해 처리되어(좌표계변환,색상등) 랜더된다.

**Comment by uzzzzin** [comment]
## 정적 라이브러리와 동적 라이브러리

### 정적 라이브러리
- .lib : 빌드할 때 오브젝트 파일이 묶여 생성되는 파일.
- 라이브러리를 사용하면 라이브러리의 코드가 프로그램에 포함되는 것.

### 동적 라이브러리
- 정적 라이브러리의 lib 파일에 해당하는 내용이 dll에 있음.
- lib에는 dll과 링킹을 위한 정보가 들어있다.
- 프로그램이 실행되고 있을 때 런타임 시에 필요할 때 로드됨.


## 디바이스란?

### 디바이스
- GPU의 메모리 관리를 진행.
- 객체를 생성하고 그것을 사용. (리소스나 셰이더들을 생성 ?)
- 리소스들을 통해 그래픽 파이프라인을 구성.

### 컨텍스트
- 객체들을 파이프라인에 연결. (리소스나 셰이더들)
- 리소스를 사용해 렌더링 명령을 생성.

### 스왑체인
- 화면에 보여지는 버퍼와, 가려져있는 버퍼가 존재하는데
그 가려진 버퍼에 모든 그림을 그림. -> 모든 그림이 그려지면 화면에 보여지는 버퍼로 교체.


## 정점이란?

꼭짓점.
위치, 색상 등의 필요한 데이터를 저장하는 구조체.

**Comment by skdy1201** [comment]
**정적 라이브러리와 동적 라이브러리**

[정적 라이브러리]
정적 라이브러리는 컴파일한 코드를 .lib 형식의 바이너리 코드에 숨겨두고, .h를 참조하면 
외부 코드를 가져다 쓸 수 있는 것.

[동적 라이브러리]
.dll과 .lib 파일로 구성되어 있으며,  바이너리 코드는 .dll 내부에 존재.
프로그램의 .exe 파일 위치에 넣어두면 동적 연결을 통해 필요할때만 라이브러리를 연결해서 사용 

**디바이스란?**

DIRECTX와 관련된 GPU 기능을 이용하기 위한 관리자 객체

1.디바이스

GPU의 메모리 관리, 객체를 생성시켜주는 객체
버퍼, 리소스 데이터 등을 생성한다.

2.컨텍스트

GPU에 명령을 수행할 수 있도록 도와주는 객체
그래픽 파이프라인 과정에서의 명령들을 수행할 수 있도록 해준다.

3.스왑체인

main window를 그리기 위해 필요한 객체
하나의 객체를 사용하지만 내부적으로 메모리를 복사해 이중 버퍼링 처럼 사용한다.



**정점이란?**

DirectX에서  Render를 하기 위해 필요한 구조체
위치 뿐 만 아니라 더 많은 정보들을 담을 수 있다.

3D 환경에서의 좌표를 다룰 수 있다.
